trigger: none

resources:
  pipelines:
    - pipeline: CI
      source: 'sheikhabuzar01.lms-project'
      trigger:
        branches:
          include:
            - main

pool:
  vmImage: 'ubuntu-latest'

stages:

  - stage: Deploy
    displayName: 'Deploy to AKS'
    jobs:
      - job: DeployToAKS
        displayName: 'Apply Kubernetes Manifests'
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: 'Connect to AKS'
            inputs:
              azureSubscription: 'azure-rm-connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az aks get-credentials --resource-group VisualStudioOnline-B7676031D19941C29CB021209999B63D --name corvit-aks-cluster --overwrite-existing

          - script: |
              echo "Current directory:"
              pwd
              echo "Files in repo:"
              ls -la
              echo "K8s folder:"
              ls -la k8s/
              kubectl apply -f k8s/deployment.yaml
              kubectl apply -f k8s/service.yaml
            displayName: 'Deploy to AKS'